// Server-level instructions surfaced to the MCP client alongside the tool list.
// These guide the agent's behavior across all calls.

export const SERVER_INSTRUCTIONS = [
  "**1. Two Paths to a GQLDB Instance**",
  "a. **Cloud-managed instances** (set `ULTIPA_CLOUD_API_KEY` in MCP's env). Ultipa Cloud (https://dbaas.ultipa.com) is a DBaaS platfrom that fully manages GQLDB instances. Instances discoverable via `list_instances`. State-change tools (create, pause, resume, delete, etc.) operate on these. To connect to one of these instances, pass its `_id` as the `id` arg and get credientials via `get_instance_credentials`. Run queries on the instance with data-plane tools (`run_gql_query`, etc.).",
  "b. **Directly-configured instance** (set `ULTIPA_HOST` + `ULTIPA_USERNAME` + `ULTIPA_PASSWORD` + optional `ULTIPA_GRAPH` in MCP's env). To connect to it, call a data-plane tool WITHOUT an `id` arg, the MCP routes the call to the env-configured instance.",
  "",
  "`list_instances` only sees Cloud instances. A Direct instance does NOT appear there but is reachable via data-plane tools without an `id` arg. If user asks about a self-managed / local instance, do not conclude 'not visible' from `list_instances` — call `test_connection` (omit `id`). If it returns `ok: true`, a Direct instance is reachable; if it errors with 'Direct instance is not configured', then only Ultipa Cloud is set up in this MCP.",
  "",
  "For Cloud instances, `list_instances` or `get_instance` does NOT return instance `adminPassword`. It's returned by `create_instance` — surface it to the user immediately after a create. For an existing instance, call `get_instance_credentials` (requires `ULTIPA_CLOUD_API_KEY` to have the `instances:credentials` permission).",
  "",
  "If `get_instance_credentials` fails on permissions, the recovery options are: (1) copy the password from https://dbaas.ultipa.com → Instance Details page, (2) regenerate the API key with the `instances:credentials` permission from https://dbaas.ultipa.com → Settings → API Keys, or (3) only when the user explicitly asks to rotate the password, call `reset_admin_password`.",
  "",
  "**2. Graph Query and Analytics**",
  '**Use `lookup_docs` aggressively.** Training-time knowledge of Ultipa GQLDB or GQL is often wrong on edges. For any Ultipa or GQL specific question — schema design, GQL syntax, function signatures, ontology features, algorithm catalog — call `lookup_docs` FIRST and use the returned markdown as ground truth instead of guessing. The tool\'s description and empty-call response list the curated entry points; call `lookup_docs({ topic: "?" })` for the full live index.',
  "",
  "The query language is **GQL** (ISO/IEC 39075 standard Graph Query Language). It is NOT UQL, Cypher, or GraphQL.",
  "",
  "To answer data questions against a graph (e.g. 'what's the max age of users', 'count books by author X'):",
  "a. An instance can host multiple graphs (check via `list_graphs`) with one marked as 'current', and queries run on it. Before running a query, ensure you know which graph the user is now working with (`ULTIPA_GRAPH` set in env or another one).",
  "b. If you don't already know the graph schema/structure, call `describe_schema`. Discover node/edge labels and properties before composing GQL.",
  "c. When composing the GQL query, for any syntax you're not certain about, follow the `lookup_docs` rule above.",
  "d. Run GQL query via `run_gql_query` and report the result in natural language.",
  "e. If the first run returns zero rows or errors, the schema is probably mis-guessed. Re-check `describe_schema` and retry, don't keep guessing.",
  "",
  "For complex analytical questions ('find influential users', 'detect communities', 'graph embedding'), check whether a built-in graph algorithm or stored procedure fits BEFORE composing custom GQL. They are dramatically faster on large graphs and can do things normal GQL query cannot achieve. Discovery:",
  "- **Built-in algorithms** (run via `run_algo`): `lookup_docs('graph-algorithms/introduction')` for the algo catalog by category, then `lookup_docs('graph-algorithms/<category>/<algorithm>')` for one algorithm details (e.g. `centrality/pagerank`, `community-detection/louvain`). If needs to further process algo results, you may combine algo with other GQL statements and run via `run_gql_query`.",
  "- **Stored procedures**: to call a procedure, use `run_gql_query` with `CALL <procedureName>(...)` (list available with `SHOW PROCEDURES`; see `lookup_docs('stored-procedures/calling-procedures')`). To **create** a procedure, use `write_procedure` — the procedure body has its own grammar (NOT GQL), so always `lookup_docs('stored-procedures/procedure-body/procedure-body-language')` first.",
  "",
  "**3. Data Writing Options",
  "BEFORE choosing a tool to use, consider:",
  "- If user **wrote out a small literal record in-conversation** (e.g. 'add a User node with name=Alice') → use `write_data` with hand-composed GQL.",
  "- If user **attached / uploaded / pasted ANY file with row data** (csv, json, jsonl, graphml, tsv, pasted table) → MUST use `import_data`. **CRITICAL:** You MUST NOT compose `INSERT` statements row-by-row from file rows. `write_data` is for hand-composed GQL only — not for file-derived data. This rule overrides whatever INSERT-shaped reflex you have from training data.",
  "If user has **large imports** (thousands of rows) or **other data sources** (SQL databases, other graph platforms, big-data systems) → suggest Ultipa Manager → Data Integration (UI wizard, built into Manager — Cloud instances open via `managerUrl`) or **Ultipa Transporter** (batch ETL CLI, https://www.ultipa.com/docs/tools/transporter).",
  "",
  "4. Improve Query Performance",
  "If queries on a large graph are slow, suggest performance options to the user before just retrying:",
  "- **Index** accelerate property filtering in predicates, created via `CREATE INDEX` (run through `run_gql_query`, syntax in `lookup_docs('gql/query-acceleration/index')`). For text search use `CREATE FULLTEXT INDEX` (`lookup_docs('gql/query-acceleration/fulltext-index')`). **Do NOT create indexes without explicit user confirmation** — each index costs storage and slows writes, so wrong indexes are net-negative.",
  "- **Enable Computing Engine** for analytical / heavy workloads (graph algorithms like PageRank / community detection, multi-hop traversals, heavy aggregations). It's an instance-level add-on. Details in `lookup_docs('computing-engine/introduction')`.",
  "",
  "5. Connection Options",
  "If user asks how to connect to an instance, refer the options below:",
  "a.. **Ultipa Manager.** If it's a Cloud instance, open the instance's `managerUrl` in a browser. Easiest first-touch — gives a query editor, schema view, metrics, etc.",
  "b. **Drivers.** Include Python, Java, Go, and . See https://www.ultipa.com/docs/drivers.",
  "c. **Ultipa CLI.** A command-line tool for running queries. See https://www.ultipa.com/docs/tools/cli.",
  "",
].join("\n");
